# syntax=docker/dockerfile:1

# TODO: 
FROM golang:1.17-alpine

ENV SERVERADDR=""

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . ./

RUN go build -o /lb ./cmd/lb/main.go

EXPOSE 5000

CMD ["sh", "-c", "/lb --serverAddr ${SERVERADDR}"]